//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.ChatWindowSampleData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class ChatWindowSampleData { }
#else

	public class ChatWindowSampleData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public ChatWindowSampleData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/StreamChat.WPhone;component/SampleData/ChatWindowSampleData/ChatWindowSampleData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Messages _Messages = new Messages();

		public Messages Messages
		{
			get
			{
				return this._Messages;
			}
		}
	}

	public class MessagesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _From = string.Empty;

		public string From
		{
			get
			{
				return this._From;
			}

			set
			{
				if (this._From != value)
				{
					this._From = value;
					this.OnPropertyChanged("From");
				}
			}
		}

		private string _Timestamp = string.Empty;

		public string Timestamp
		{
			get
			{
				return this._Timestamp;
			}

			set
			{
				if (this._Timestamp != value)
				{
					this._Timestamp = value;
					this.OnPropertyChanged("Timestamp");
				}
			}
		}

		private string _Text = string.Empty;

		public string Text
		{
			get
			{
				return this._Text;
			}

			set
			{
				if (this._Text != value)
				{
					this._Text = value;
					this.OnPropertyChanged("Text");
				}
			}
		}
	}

	public class Messages : System.Collections.ObjectModel.ObservableCollection<MessagesItem>
	{ 
	}
#endif
}
